version: "3"
services:
  openldap:
    build: docker/openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - .:/input:ro
      - ./output:/output
    environment:
      - CERT_FILENAME=/input/certs/server.pem
      - KEY_FILENAME=/input/certs/server-key.pem
      - CA_FILENAME=/input/certs/ca.pem
  ldap-client:
    build: docker/ldap-client
    ports:
      - "2222:22"
    volumes:
      - .:/input:ro
